name: CI - Build, Test & Docker

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.java'
      - '**/pom.xml'
      - 'Dockerfile'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Necesario para poder publicar en GHCR
permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven - Build & Test (ms-clientes)
        run: mvn -B -DskipTests=false -pl ms-clientes -am clean verify

      - name: Upload ms-clientes JAR
        uses: actions/upload-artifact@v4
        with:
          name: ms-clientes-jar
          path: ms-clientes/target/*.jar
          if-no-files-found: error

  docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login a GHCR usando GITHUB_TOKEN (no hace falta PAT ni secrets)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Metadatos / tags de imagen
      - name: Docker metadata (GHCR)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/clientes-webapp
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      # Construye y PUBLICA a GHCR
      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- OPCIONAL: subir la imagen como artefacto .tar por si no quieres usar registry ----
      - name: Build (load into runner)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: clientes-webapp:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save image as tar
        run: docker save clientes-webapp:ci -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tar
          path: image.tar
