name: CI - Build, Test & Docker

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.java'
      - '**/pom.xml'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven - Build (all modules needed for ms-clientes)
        run: mvn -B -DskipTests=false -pl ms-clientes -am clean verify

      - name: Upload ms-clientes JAR
        uses: actions/upload-artifact@v4
        with:
          name: ms-clientes-jar
          path: ms-clientes/target/*.jar
          if-no-files-found: error

  docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.ref_type == 'branch' }}  # corre en branches; puedes ajustar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Inicia sesión si configuraste secretos para publicar la imagen
      - name: Docker login (Docker Hub)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker login (GitHub Container Registry)
        if: ${{ secrets.GHCR_USERNAME && secrets.GHCR_TOKEN }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME && format('{0}/clientes-webapp', secrets.DOCKERHUB_USERNAME) }}
            ${{ secrets.GHCR_USERNAME && format('ghcr.io/{0}/clientes-webapp', secrets.GHCR_USERNAME) }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build (and optionally push) Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ (secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN) || (secrets.GHCR_USERNAME && secrets.GHCR_TOKEN) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
